sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: WNQ0J4kExmXFKxDFbE8fwBqgx+yWyEi+d+uB4YFS8lwS/By+rkSWKNWT25xAzQoa1j+KVDewtgkPVBooFqdasR9Jb7IN2l5SND+0Ompg4GrRNhfS+oGLE7VBg7N3N10XaISxelid1w6oWFL26rp1mjBjdYQh0t3DWuUDBFdkBWH3ZkTXoHHY/2Yix7vudNf8rz6VMV3dbPP7AI3B6nvKOFy+vGH/xGZhcAtQhQ7A7GMg+ipUopHHGvEJCmHLEunnm/x5TI6SZ/nyPQDoBqcTXAB5F7eWnp7z8TVgTDHXiEFFANlxIGSe8ZlEZxV86InbFu/KpiaWveniKfNYtI+ziWK5DMkpj/Do7/HQFyFSX7i8xzPDR2m4A84txjdfGafnHr64gfralr4a+OrxV/Won6eJ2uDfgoSG2jMz6fEh5QtY622ZtzpghtNMhqFOSpYR0uIz535b5aZit33bNMZ2rWSLYgDwboKgYsf4APDTT34BND1u14KnI54hh7PcckadvumYOARaCz/+hxzLYj99nlGJcH3fL3w+8t4K6LJxnhUf/7kR16bXqk67Zf+cXZjhiHMkPV7p1Z2AZYYZSyc790c9EzqoQUhohFor4kJIJ8J8WEBYL+W5SGHqpvCFfBGfrS/3keUbptcJrolm+sAOk2qppu7H4UmH+c0O5UYKUfQ=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/King-Arthur-and-the-Knights-of-the-Round-Table_36462
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy